version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:15-alpine
    container_name: booking-postgres
    restart: unless-stopped
    
    environment:
      # Database credentials
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_DB: booking_db
      
    ports:
      # Map container port 5432 to host port 5432
      - "5432:5432"
      
    volumes:
      # Persist data in a named volume
      - postgres_data:/var/lib/postgresql/data
    
    # Verify that PostgreSQL is ready before accepting connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user -d booking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

# Define volumes
volumes:
  postgres_data:
    driver: local
